### ISSUE TITLE
Character Spritesheets

### ISSUE THREAD

**Issue by omegaleo** [omegaleo/OfficeRebel#1]
We need spritesheets for the following:

- [x] Character - Done in #15 
- [x] IT Guy/Narrator - Done in #16 
- [x] Boss - Done in #16 
- [x] Office Worker A - Done in #16 
- [x] Office Worker B - Done in #16 
- [x] Character (Female)(Allow player to choose?) - Done in #16
