### ISSUE TITLE
Boss Logic

### ISSUE THREAD

**Issue by omegaleo** [omegaleo/OfficeRebel#13]
Implement logic for the boss:

- [x] ~~When suspicion is high, boss opens the door to his office, comes out and starts to roam around the player~~ Boss roams around the office constantly, when suspicion is high he'll roam around the player more often. - Done in #18 
- [x] Put big items in front of the boss to block him and make him have to move them back to place (Gain around 2.5 minutes) - Done in #19
- [x] If player breaks a rule with the boss nearby, chances are they're going to get a game over or at least a warning depending on if they already have a warning or the item that was stolen. - Partially done in #19 - Done in #22, doesn't have warning system
