### ISSUE TITLE
Narrator Logic

### ISSUE THREAD

**Issue by omegaleo** [omegaleo/OfficeRebel#6]
Logic needed:

- [x] Voice lines - #5 - Done in #20
- [x] Reporting to the boss - Done in #20
- [x] Duct taping - Done in #20
